# Generated by Django 3.2.14 on 2022-07-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasksList', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
